import type { UserRole } from '@/features/auth/types/auth.types';
import type { Permission } from '@/features/rbac/types/permission.types';

/**
 * Elevated permissions per role. Every authenticated role additionally
 * carries an implicit baseline of `profile.view_own` / `profile.update_own`
 * (see hasPermission in utils/permissionHelpers.ts), so those two are
 * deliberately omitted here rather than repeated 24 times.
 *
 * Framework-level and business-module permissions.
 *
 * `reports.view`/`reports.export` (Reports & Analytics) follow a derived
 * rule rather than being assigned ad hoc: `reports.view` goes to any role
 * holding at least one of `academic.view`/`employee.view`/`learner.view`
 * (a role with none of the three would see an empty Reports section, so
 * granting it would be pointless); `reports.export` — deliberately
 * narrower, same shape as `learner.view_sensitive` being narrower than
 * `learner.view` — goes only to roles additionally holding at least one
 * `.manage`-tier permission among `academic.manage`/`employee.manage`/
 * `learner.manage`/`learner.manage_medical`, since removing data from the
 * app as a file is a more consequential action than viewing it on screen.
 */
export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  super_administrator: [
    'school.view',
    'school.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
  ],
  platform_administrator: [
    'school.view',
    'school.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
  ],
  support_engineer: ['school.view', 'profile.view_any'],
  school_owner: [
    'school.view',
    'school.manage',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
  ],
  principal: [
    'school.view',
    'school.manage',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.view_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'reports.view',
    'reports.export',
  ],
  vice_principal: [
    'school.view',
    'profile.view_any',
    'learner.view',
    'learner.view_behaviour',
    'learner.manage_behaviour',
  ],
  department_head: [
    'school.view',
    'profile.view_any',
    'learner.view',
    'learner.view_behaviour',
    'learner.manage_behaviour',
  ],
  hr_manager: [
    'school.view',
    'profile.view_any',
    'profile.manage_any',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
  ],
  finance_manager: ['school.view', 'learner.view', 'learner.view_financial', 'learner.manage_financial'],
  accountant: ['school.view', 'learner.view', 'learner.view_financial', 'learner.manage_financial'],
  receptionist: ['school.view', 'profile.view_any'],
  admissions_officer: [
    'school.view',
    'profile.view_any',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'guardian.view',
    'guardian.manage',
    'reports.view',
    'reports.export',
  ],
  librarian: ['school.view'],
  transport_coordinator: ['school.view'],
  sports_coordinator: ['school.view'],
  medical_officer: [
    'school.view',
    'learner.view',
    'learner.view_medical',
    'learner.manage_medical',
    'reports.view',
    'reports.export',
  ],
  auditor: ['school.view', 'profile.view_any'],
  teacher: [
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reports.view',
  ],
  class_teacher: [
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reports.view',
  ],
  subject_teacher: [
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reports.view',
  ],
  parent: [],
  guardian: [],
  learner: [],
  guest: [],
};
