import type { UserRole } from '@/features/auth/types/auth.types';
import type { Permission } from '@/features/rbac/types/permission.types';

/**
 * Elevated permissions per role. Every authenticated role additionally
 * carries an implicit baseline of `profile.view_own` / `profile.update_own`
 * (see hasPermission in utils/permissionHelpers.ts), so those two are
 * deliberately omitted here rather than repeated 24 times.
 *
 * Framework-level and business-module permissions.
 *
 * `reports.view`/`reports.export` (Reports & Analytics) follow a derived
 * rule rather than being assigned ad hoc: `reports.view` goes to any role
 * holding at least one of `academic.view`/`employee.view`/`learner.view`
 * (a role with none of the three would see an empty Reports section, so
 * granting it would be pointless); `reports.export` — deliberately
 * narrower, same shape as `learner.view_sensitive` being narrower than
 * `learner.view` — goes only to roles additionally holding at least one
 * `.manage`-tier permission among `academic.manage`/`employee.manage`/
 * `learner.manage`/`learner.manage_medical`, since removing data from the
 * app as a file is a more consequential action than viewing it on screen.
 */
export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  platform_owner: [
    'compliance.view',
    'compliance.manage',
    'operations.view',
    'operations.manage',
    'transport.view',
    'transport.manage',
    'school.view',
    'school.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reportcard.approve',
    'admission.view',
    'admission.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'learner.view_safeguarding',
    'learner.manage_safeguarding',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
    'government.view',
    'government.export',
    'government.manage',
  ],
  super_administrator: [
    'compliance.view',
    'compliance.manage',
    'operations.view',
    'operations.manage',
    'transport.view',
    'transport.manage',
    'school.view',
    'school.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reportcard.approve',
    'admission.view',
    'admission.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'learner.view_safeguarding',
    'learner.manage_safeguarding',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
    'government.view',
    'government.export',
    'government.manage',
  ],
  platform_administrator: [
    'compliance.view',
    'compliance.manage',
    'operations.view',
    'operations.manage',
    'transport.view',
    'transport.manage',
    'school.view',
    'school.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reportcard.approve',
    'admission.view',
    'admission.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'learner.view_safeguarding',
    'learner.manage_safeguarding',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
    'government.view',
    'government.export',
    'government.manage',
  ],
  support_engineer: ['school.view', 'profile.view_any'],
  school_owner: [
    'compliance.view',
    'compliance.manage',
    'operations.view',
    'operations.manage',
    'transport.view',
    'transport.manage',
    'school.view',
    'school.manage',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reportcard.approve',
    'admission.view',
    'admission.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.manage_medical',
    'learner.view_financial',
    'learner.manage_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'learner.view_safeguarding',
    'learner.manage_safeguarding',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
    'government.view',
    'government.export',
  ],
  principal: [
    'compliance.view',
    'compliance.manage',
    'operations.view',
    'operations.manage',
    'transport.view',
    'transport.manage',
    'school.view',
    'school.manage',
    'profile.view_any',
    'profile.manage_any',
    'academic.view',
    'academic.manage',
    'timetable.view',
    'timetable.manage',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reportcard.approve',
    'admission.view',
    'admission.manage',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'learner.view_medical',
    'learner.view_financial',
    'learner.view_behaviour',
    'learner.manage_behaviour',
    'learner.view_safeguarding',
    'learner.manage_safeguarding',
    'guardian.view',
    'guardian.manage',
    'employee.view',
    'reports.view',
    'reports.export',
    'government.view',
    'government.export',
  ],
  vice_principal: [
    'operations.view',
    'operations.manage',
    'transport.view',
    'school.view',
    'profile.view_any',
    'reportcard.view',
    'admission.view',
    'learner.view',
    'learner.view_behaviour',
    'learner.manage_behaviour',
  ],
  department_head: [
    'school.view',
    'profile.view_any',
    'reportcard.view',
    'reportcard.manage',
    'learner.view',
    'learner.view_behaviour',
    'learner.manage_behaviour',
  ],
  hr_manager: [
    'school.view',
    'profile.view_any',
    'profile.manage_any',
    'employee.view',
    'employee.manage',
    'reports.view',
    'reports.export',
  ],
  finance_manager: [
    'school.view',
    'learner.view',
    'learner.view_financial',
    'learner.manage_financial',
  ],
  accountant: ['school.view', 'learner.view', 'learner.view_financial', 'learner.manage_financial'],
  receptionist: ['school.view', 'profile.view_any', 'admission.view'],
  admissions_officer: [
    'school.view',
    'admission.view',
    'admission.manage',
    'profile.view_any',
    'learner.view',
    'learner.manage',
    'learner.view_sensitive',
    'guardian.view',
    'guardian.manage',
    'reports.view',
    'reports.export',
  ],
  librarian: ['school.view', 'operations.view', 'operations.manage'],
  transport_coordinator: [
    'school.view',
    'transport.view',
    'transport.manage',
    'operations.view',
    'operations.manage',
  ],
  sports_coordinator: ['school.view', 'operations.view', 'operations.manage'],
  asset_manager: ['school.view', 'operations.view', 'operations.manage'],
  boarding_manager: ['school.view', 'operations.view', 'operations.manage'],
  events_coordinator: ['school.view', 'operations.view', 'operations.manage'],
  governance_officer: ['school.view', 'operations.view', 'operations.manage'],
  procurement_officer: ['school.view', 'operations.view', 'operations.manage'],
  medical_officer: [
    'school.view',
    'learner.view',
    'learner.view_medical',
    'learner.manage_medical',
    'reports.view',
    'reports.export',
  ],
  auditor: ['school.view', 'profile.view_any'],
  teacher: [
    'transport.view',
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reports.view',
  ],
  class_teacher: [
    'transport.view',
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reports.view',
  ],
  subject_teacher: [
    'transport.view',
    'school.view',
    'academic.view',
    'timetable.view',
    'attendance.view',
    'attendance.manage',
    'assessment.view',
    'assessment.manage',
    'reportcard.view',
    'reportcard.manage',
    'reports.view',
  ],
  // Reads aggregated reports for the schools in their assigned areas; the
  // database decides which schools (reporting_school_ids()).
  education_official: ['government.view', 'government.export'],
  parent: [],
  guardian: [],
  learner: [],
  guest: [],
};
