/**
 * Framework-level and business-module permission catalogue.
 * Extend this union as each new module lands its own permission set.
 */
export type Permission =
  | 'school.view'
  | 'school.manage'
  | 'tenant.switch'
  | 'profile.view_own'
  | 'profile.update_own'
  | 'profile.view_any'
  | 'profile.manage_any'
  | 'academic.view'
  | 'academic.manage'
  | 'timetable.view'
  | 'timetable.manage'
  | 'attendance.view'
  | 'attendance.manage'
  | 'assessment.view'
  | 'assessment.manage'
  | 'reportcard.view'
  | 'reportcard.manage'
  | 'reportcard.approve'
  | 'admission.view'
  | 'admission.manage'
  | 'learner.view'
  | 'learner.manage'
  | 'learner.view_sensitive'
  | 'learner.view_medical'
  | 'learner.manage_medical'
  | 'learner.view_financial'
  | 'learner.manage_financial'
  | 'learner.view_behaviour'
  | 'learner.manage_behaviour'
  | 'learner.view_safeguarding'
  | 'learner.manage_safeguarding'
  | 'guardian.view'
  | 'guardian.manage'
  | 'employee.view'
  | 'employee.manage'
  | 'reports.view'
  | 'reports.export';
